name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run release-please
        uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: gridmapper
          bump-minor-pre-major: true
          # set draft to true if you prefer the release to be created as draft
          # create-release: true
